DROP DATABASE IF EXISTS `projnotas`;
CREATE DATABASE `projnotas`;
USE `projnotas`;

DROP USER IF EXISTS 'es2lp3n2'@'localhost';
CREATE USER 'es2lp3n2'@'localhost' IDENTIFIED BY 'nsvw@#220Z';
GRANT SELECT, INSERT, UPDATE, DELETE ON `projnotas` . * TO 'es2lp3n2'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE `tbTeachingInstitutions`
(
  `id` SMALLINT UNSIGNED AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY(`id`),
  UNIQUE(`name`)
);

CREATE TABLE `tbUsers`
(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `userName` VARCHAR(100) NOT NULL,
  `password` VARBINARY(255) NOT NULL,
  `idTeachingInstitution` SMALLINT UNSIGNED,
  `type` CHAR(1) NOT NULL,
  PRIMARY KEY(`id`),
  FOREIGN KEY(`idTeachingInstitution`) REFERENCES `tbTeachingInstitutions`(`id`),
  UNIQUE(`userName`)
);

CREATE TABLE `tbSubjects`
(
  `id` SMALLINT UNSIGNED AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY(`id`),
  UNIQUE(`description`)
);

CREATE TABLE `tbSubjectsXUsers`
(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `idSubject` SMALLINT UNSIGNED NOT NULL,
  `idTeachingInstitution` SMALLINT UNSIGNED NOT NULL,
  `idUser` INT UNSIGNED NOT NULL,
  `grade` DECIMAL(3, 1) NOT NULL,
  `semester` TINYINT UNSIGNED NOT NULL,
  `year` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(`id`),
  FOREIGN KEY(`idSubject`) REFERENCES `tbSubjects`(`id`),
  FOREIGN KEY(`idTeachingInstitution`) REFERENCES `tbTeachingInstitutions`(`id`),
  FOREIGN KEY(`idUser`) REFERENCES `tbUsers`(`id`)
);

CREATE TABLE `tbSubjectsXTeachingInstitutions`
(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `idSubject` SMALLINT UNSIGNED NOT NULL,
  `idTeachingInstitution` SMALLINT UNSIGNED NOT NULL,
  `active` CHAR(1) NOT NULL,
  PRIMARY KEY(`id`),
  FOREIGN KEY(`idSubject`) REFERENCES `tbSubjects`(`id`),
  FOREIGN KEY(`idTeachingInstitution`) REFERENCES `tbTeachingInstitutions`(`id`)
);

INSERT INTO `tbSubjects`
  (`description`)
VALUES
  ('Acionamentos Elétricos'),
  ('Ações Assistivas e Inclusão Social'),
  ('Administração da Produção'),
  ('Administração de Sistemas da Informação'),
  ('Administração para Engenharia'),
  ('Álgebra Linear e Geometria Analítica'),
  ('Algoritmos I'),
  ('Algoritmos II'),
  ('Algoritmos e Programação'),
  ('Ambiente de Simulação'),
  ('Análise Contábil e Financeira'),
  ('Análise Sensorial'),
  ('Arquitetura de Computadores I'),
  ('Arquitetura de Computadores II'),
  ('Automação Pneumática e Hidráulica'),
  ('Banco de Dados I'),
  ('Banco de Dados II'),
  ('Bioquímica dos Alimentos'),
  ('Cálculo Diferencial e Integral I'),
  ('Cálculo Diferencial e Integral II'),
  ('Cálculo Diferencial e Integral III'),
  ('Cálculo Numérico'),
  ('CAM'),
  ('Cidadania e Inclusão'),
  ('Ciência do Ambiente e Desenvolvimento Sustentável'),
  ('Ciência dos Materiais'),
  ('Circuitos Elétricos'),
  ('CNC'),
  ('Compiladores'),
  ('Comunicação de Dados'),
  ('Comunicação e Mídias Digitais'),
  ('Comunicação Empresarial'),
  ('Contabilidade e Custos'),
  ('Contabilidade para Administradores'),
  ('Controladores Programáveis'),
  ('Controle e Automação'),
  ('Controle e Servomecanismo'),
  ('Desenho Técnico + CAD'),
  ('Desenho Técnico Avançado'),
  ('Desenvolvimento de Produtos'),
  ('Desenvolvimento Interpessoal'),
  ('Direito Aplicado à Empresa'),
  ('Direito Digital'),
  ('Direito e Legislação'),
  ('Economia'),
  ('Economia Industrial '),
  ('Elementos de Máquinas'),
  ('Eletricidade Aplicada'),
  ('Eletrônica Analógica'),
  ('Eletrônica Digital'),
  ('Eletrotécnica e Instalações Elétricas '),
  ('Embalagens para Alimentos'),
  ('Empreendedorismo e Plano de Negócios'),
  ('Engenharia Bioquímica'),
  ('Engenharia de Software I'),
  ('Engenharia de Software II'),
  ('Estatística'),
  ('Estatística Aplicada'),
  ('Estatística Aplicada à Gestão'),
  ('Estratégia Competitiva e Corporativa'),
  ('Estratégia e Simulação Empresarial'),
  ('Estrutura de Dados'),
  ('Estruturas Organizacionais'),
  ('Estudos das Organizações e suas Culturas'),
  ('Ética e Cidadania'),
  ('Ética Organizacional e Profissional'),
  ('Fenômenos de Transporte'),
  ('Ferramentas da Qualidade'),
  ('Ferramentas de Gestão Integrada'),
  ('Física Geral e Experimental I'),
  ('Física Geral e Experimental II'),
  ('Física Geral e Experimental III'),
  ('Físico-química'),
  ('Fundamentos de Tecnologia dos Alimentos'),
  ('Gestão Ambiental e Tratamento de Resíduos'),
  ('Gestão da Cadeia de Suprimentos'),
  ('Gestão da Qualidade'),
  ('Gestão da Qualidade e Produtividade'),
  ('Gestão da Qualidade e Segurança dos Alimentos'),
  ('Gestão da Tecnologia da Informação'),
  ('Gestão de Pessoas'),
  ('Gestão de Processos Organizacionais'),
  ('Gestão de Produção e Operações'),
  ('Gestão de Projetos'),
  ('Gestão de Projetos na Engenharia de Computação'),
  ('Gestão de Projetos na Engenharia de Controle e Automação'),
  ('Gestão Do Conhecimento e Inteligência Competitiva'),
  ('Gestão do Relacionamento Público e Privado'),
  ('Gestão Empreendedora'),
  ('Gestão Estratégica da Informação'),
  ('Gestão Estratégica de Custos'),
  ('Gestão Financeira'),
  ('Gestão Mercadológica'),
  ('Higiene e Sanitização de Alimentos'),
  ('Higiene e Segurança do Trabalho'),
  ('Informática Aplicada'),
  ('Instalações Industriais'),
  ('Instrumentação e Controle de Processos'),
  ('Instrumentação Industrial'),
  ('Inteligência Artificial'),
  ('Introdução à Computação'),
  ('Introdução à Economia'),
  ('Introdução à Engenharia de Alimentos'),
  ('Introdução à Engenharia de Computação'),
  ('Introdução à Engenharia de Controle e Automação'),
  ('Introdução à Marketing'),
  ('Legislação e Planejamento Tributário'),
  ('Libras'),
  ('Linguagem de Programação I'),
  ('Linguagem de Programação II'),
  ('Linguagem de Programação III'),
  ('Linguagem de Programação IV'),
  ('Linguagens Formais e Autômatos'),
  ('Macro e Micro Economia'),
  ('Manufatura Integrada por Computador'),
  ('Manutenção Mecânica'),
  ('Matemática Financeira'),
  ('Mecânica Geral'),
  ('Metodologia Científica'),
  ('Metodologia de Pesquisa Científica'),
  ('Metodologia do Trabalho Científico'),
  ('Métodos Quantitativos'),
  ('Metrologia'),
  ('Microbiologia dos Alimentos'),
  ('Microbiologia Geral'),
  ('Modelagem de Sistemas Dinâmicos'),
  ('Modelos de Análises de Decisões'),
  ('Modelos de Gestão e Liderança'),
  ('Nutrição e Toxicologia'),
  ('Operações de Usinagem e Soldagem'),
  ('Operações Unitárias I'),
  ('Operações Unitárias II'),
  ('Pesquisa Operacional'),
  ('Planejamento e Projetos Industriais'),
  ('Princípios de Administração'),
  ('Probabilidade e Estatística'),
  ('Processo Administrativo'),
  ('Processos de Conformação Mecânica'),
  ('Processos de Fabricação'),
  ('Processos Metalúrgicos'),
  ('Produção de Conjuntos Mecânicos'),
  ('Programação Mobile'),
  ('Programação Orientada a Objetos'),
  ('Programação Visual'),
  ('Projeto Interdisciplinar I'),
  ('Projeto Interdisciplinar II'),
  ('Qualidade de Software'),
  ('Química Analítica'),
  ('Química dos Alimentos I'),
  ('Química dos Alimentos II'),
  ('Química Geral e Tecnológica'),
  ('Química Orgânica'),
  ('Recursos Materiais e Patrimoniais'),
  ('Rede de Computadores'),
  ('Redes Industriais'),
  ('Refrigeração'),
  ('Responsabilidade Social e Ambiental das Empresas'),
  ('Robótica'),
  ('Serviços de Rede'),
  ('Sistemas de Controle Discreto'),
  ('Sistemas de Informação'),
  ('Sistemas Digitais'),
  ('Sistemas Digitais e Microcontroladores'),
  ('Sistemas Distribuídos'),
  ('Sistemas Microprocessados'),
  ('Sistemas Operacionais'),
  ('Sistemas Supervisórios'),
  ('Sistemas Térmicos'),
  ('Tecnologia de Bebidas e Óleos'),
  ('Tecnologia de Frutas e Hort., Prod. Açuc. e Panif.'),
  ('Tecnologia de Leite e Carnes'),
  ('Tecnologia de Máquinas e Ferramentas'),
  ('Tecnologia e Resistência dos Materiais'),
  ('Termodinâmica'),
  ('Teoria Geral da Administração'),
  ('Tópicos Avançados de Administração'),
  ('Tópicos Avançados de Gestão de Projetos'),
  ('Tópicos Avançados em Redes'),
  ('Tópicos Especiais de Engenharia'),
  ('Trabalho de Conclusão de Curso I'),
  ('Trabalho de Conclusão de Curso II'),
  ('Viabilidade Econômica Financeira de Negócios'),
  ('Vibrações Mecânicas');
